Repository pagopa/pagopa-wisp-soap-converter, pull requests merged in 2024-07, with the labels that each got.

#14 [PAGOPA-1942] fix: removed redundant sessionId field
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  version.sbt
Labels: patch, size/small

#15 fix: fixed JUnit tests
  wispsoapconverter/src/test/scala/it/gov/pagopa/tests/BaseUnitTest.scala
  wispsoapconverter/src/test/scala/it/gov/pagopa/tests/InviaRPTUnitTests.scala
Labels: size/large, patch

#17 [PAGOPA-1908] cd: Update values-prod.yaml
  helm/values-prod.yaml
Labels: ignore-for-release, size/small

#16 [PAGOPA-1908] WISP soap converter
  helm/Chart.yaml
  helm/values-prod.yaml
  version.sbt
Labels: size/small

#18 [PAGOPA-1908] cd: Update values-prod.yaml
  helm/values-prod.yaml
Labels: size/small
